name: robot-octodollop # you probably want to 'snapcraft register <name>'
version: '0.1.11+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Playground for running FRC robots # 79 char long summary
description: |
  Octodollop is a playground for Python that combines Qt and RobotPy together.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps: 
  robot-octodollop:
    command: robot-octodollop

parts:
  robot-octodollop:
    source: https://github.com/dmsmechamonarchs2896/robot-octodollop.git
    # See 'snapcraft plugins'
    plugin: python3
    plugin: qmake
    plugin: python
